@startuml

    entity "Договор" as CONTRACT {
        * Номер договора
        Дата договора
        Тип договора
        Поставщик
        Плательщик
        Валюта
    }

    entity "Этап договора" as CONTRACT_STAGE {
        * Этап договора
        * Номер договора
        Дата начала
        Дата окончания
        Единица измерения
        Сумма
        Количество
    }

    entity "Фактура" as INVOICE {
        * Номер документа выполнения
        * Номер этапа
        Позиция фактуры
        Дата выполнения
        Сумма выполнения
        Количество
    }

    entity "Документ выполнения" as EXECUTION_DOCUMENT {
        * Номер документа выполнения
        Дата документа
        Тип документа
        Валюта выполнения
    }

    CONTRACT ||..|{ CONTRACT_STAGE
    INVOICE  ||..|| CONTRACT_STAGE
    EXECUTION_DOCUMENT ||..|{ INVOICE

@enduml